/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package obstextmanager;

import java.awt.event.KeyEvent;

/**
 *
 * @author Andres
 */
public class OBSTextManagerGUI extends javax.swing.JFrame {

    /**
     * Creates new form OBSTextManagerGUI
     */
    public OBSTextManagerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jugador1Label = new javax.swing.JLabel();
        jugador1Text = new javax.swing.JTextField();
        punt1Label = new javax.swing.JLabel();
        punt1Text = new javax.swing.JTextField();
        jugador2Label = new javax.swing.JLabel();
        jugador2Text = new javax.swing.JTextField();
        punt2Label = new javax.swing.JLabel();
        punt2Text = new javax.swing.JTextField();
        twitter1Label = new javax.swing.JLabel();
        twitter1Text = new javax.swing.JTextField();
        rondaLabel = new javax.swing.JLabel();
        rondaText = new javax.swing.JTextField();
        twitter2Label = new javax.swing.JLabel();
        twitter2Text = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        writeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(4, 4));

        jugador1Label.setText("Jugador 1");
        getContentPane().add(jugador1Label);

        jugador1Text.setText("jTextField2");
        jugador1Text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jugador1TextFocusGained(evt);
            }
        });
        jugador1Text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jugador1TextMouseClicked(evt);
            }
        });
        jugador1Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugador1TextActionPerformed(evt);
            }
        });
        getContentPane().add(jugador1Text);

        punt1Label.setText("Puntuacion 1");
        getContentPane().add(punt1Label);

        punt1Text.setText("jTextField1");
        punt1Text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                punt1TextFocusGained(evt);
            }
        });
        punt1Text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                punt1TextMouseClicked(evt);
            }
        });
        getContentPane().add(punt1Text);

        jugador2Label.setText("Jugador 2");
        getContentPane().add(jugador2Label);

        jugador2Text.setText("jTextField3");
        jugador2Text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jugador2TextFocusGained(evt);
            }
        });
        jugador2Text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jugador2TextMouseClicked(evt);
            }
        });
        getContentPane().add(jugador2Text);

        punt2Label.setText("Puntuacion 2");
        getContentPane().add(punt2Label);

        punt2Text.setText("jTextField6");
        punt2Text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                punt2TextFocusGained(evt);
            }
        });
        punt2Text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                punt2TextMouseClicked(evt);
            }
        });
        getContentPane().add(punt2Text);

        twitter1Label.setText("Twitter 1");
        getContentPane().add(twitter1Label);

        twitter1Text.setText("jTextField4");
        twitter1Text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                twitter1TextFocusGained(evt);
            }
        });
        twitter1Text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twitter1TextMouseClicked(evt);
            }
        });
        getContentPane().add(twitter1Text);

        rondaLabel.setText("Ronda");
        getContentPane().add(rondaLabel);

        rondaText.setText("jTextField7");
        rondaText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rondaTextFocusGained(evt);
            }
        });
        rondaText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rondaTextMouseClicked(evt);
            }
        });
        getContentPane().add(rondaText);

        twitter2Label.setText("Twitter 2");
        getContentPane().add(twitter2Label);

        twitter2Text.setText("jTextField5");
        twitter2Text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                twitter2TextFocusGained(evt);
            }
        });
        twitter2Text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twitter2TextMouseClicked(evt);
            }
        });
        getContentPane().add(twitter2Text);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);

        writeButton.setText("Escribir");
        writeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                writeButtonMouseClicked(evt);
            }
        });
        writeButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                writeButtonKeyPressed(evt);
            }
        });
        getContentPane().add(writeButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jugador1TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugador1TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jugador1TextActionPerformed

    private void jugador1TextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jugador1TextMouseClicked
        // TODO add your handling code here:
        javax.swing.JTextField field = (javax.swing.JTextField) evt.getSource();
        field.setSelectionStart(0);
        field.setSelectionEnd(field.getText().length());
    }//GEN-LAST:event_jugador1TextMouseClicked

    private void jugador2TextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jugador2TextMouseClicked
        // TODO add your handling code here:
        javax.swing.JTextField field = (javax.swing.JTextField) evt.getSource();
        field.setSelectionStart(0);
        field.setSelectionEnd(field.getText().length());
    }//GEN-LAST:event_jugador2TextMouseClicked

    private void twitter1TextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twitter1TextMouseClicked
        // TODO add your handling code here:
        javax.swing.JTextField field = (javax.swing.JTextField) evt.getSource();
        field.setSelectionStart(0);
        field.setSelectionEnd(field.getText().length());
    }//GEN-LAST:event_twitter1TextMouseClicked

    private void twitter2TextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twitter2TextMouseClicked
        // TODO add your handling code here:
        javax.swing.JTextField field = (javax.swing.JTextField) evt.getSource();
        field.setSelectionStart(0);
        field.setSelectionEnd(field.getText().length());
    }//GEN-LAST:event_twitter2TextMouseClicked

    private void punt1TextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_punt1TextMouseClicked
        // TODO add your handling code here:
        javax.swing.JTextField field = (javax.swing.JTextField) evt.getSource();
        field.setSelectionStart(0);
        field.setSelectionEnd(field.getText().length());
    }//GEN-LAST:event_punt1TextMouseClicked

    private void punt2TextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_punt2TextMouseClicked
        // TODO add your handling code here:
        javax.swing.JTextField field = (javax.swing.JTextField) evt.getSource();
        field.setSelectionStart(0);
        field.setSelectionEnd(field.getText().length());
    }//GEN-LAST:event_punt2TextMouseClicked

    private void rondaTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rondaTextMouseClicked
        // TODO add your handling code here:
        javax.swing.JTextField field = (javax.swing.JTextField) evt.getSource();
        field.setSelectionStart(0);
        field.setSelectionEnd(field.getText().length());
    }//GEN-LAST:event_rondaTextMouseClicked

    private void writeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_writeButtonMouseClicked
        // TODO add your handling code here:
        OBSTextManager.writeText("jugador1", jugador1Text.getText());
        OBSTextManager.writeText("jugador2", jugador2Text.getText());
        OBSTextManager.writeText("twitter1", twitter1Text.getText());
        OBSTextManager.writeText("twitter2", twitter2Text.getText());
        OBSTextManager.writeText("punt1", punt1Text.getText());
        OBSTextManager.writeText("punt2", punt2Text.getText());
        OBSTextManager.writeText("ronda", rondaText.getText());
    }//GEN-LAST:event_writeButtonMouseClicked

    private void jugador1TextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jugador1TextFocusGained
        // TODO add your handling code here:
        javax.swing.JTextField field = (javax.swing.JTextField) evt.getSource();
        field.setSelectionStart(0);
        field.setSelectionEnd(field.getText().length());
    }//GEN-LAST:event_jugador1TextFocusGained

    private void jugador2TextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jugador2TextFocusGained
        // TODO add your handling code here:
        javax.swing.JTextField field = (javax.swing.JTextField) evt.getSource();
        field.setSelectionStart(0);
        field.setSelectionEnd(field.getText().length());
    }//GEN-LAST:event_jugador2TextFocusGained

    private void twitter1TextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_twitter1TextFocusGained
        // TODO add your handling code here:
        javax.swing.JTextField field = (javax.swing.JTextField) evt.getSource();
        field.setSelectionStart(0);
        field.setSelectionEnd(field.getText().length());
    }//GEN-LAST:event_twitter1TextFocusGained

    private void twitter2TextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_twitter2TextFocusGained
        // TODO add your handling code here:
        javax.swing.JTextField field = (javax.swing.JTextField) evt.getSource();
        field.setSelectionStart(0);
        field.setSelectionEnd(field.getText().length());
    }//GEN-LAST:event_twitter2TextFocusGained

    private void punt1TextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_punt1TextFocusGained
        // TODO add your handling code here:
        javax.swing.JTextField field = (javax.swing.JTextField) evt.getSource();
        field.setSelectionStart(0);
        field.setSelectionEnd(field.getText().length());
    }//GEN-LAST:event_punt1TextFocusGained

    private void punt2TextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_punt2TextFocusGained
        // TODO add your handling code here:
        javax.swing.JTextField field = (javax.swing.JTextField) evt.getSource();
        field.setSelectionStart(0);
        field.setSelectionEnd(field.getText().length());
    }//GEN-LAST:event_punt2TextFocusGained

    private void rondaTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rondaTextFocusGained
        // TODO add your handling code here:
        javax.swing.JTextField field = (javax.swing.JTextField) evt.getSource();
        field.setSelectionStart(0);
        field.setSelectionEnd(field.getText().length());
    }//GEN-LAST:event_rondaTextFocusGained

    private void writeButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_writeButtonKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            OBSTextManager.writeText("jugador1", jugador1Text.getText());
            OBSTextManager.writeText("jugador2", jugador2Text.getText());
            OBSTextManager.writeText("twitter1", twitter1Text.getText());
            OBSTextManager.writeText("twitter2", twitter2Text.getText());
            OBSTextManager.writeText("punt1", punt1Text.getText());
            OBSTextManager.writeText("punt2", punt2Text.getText());
            OBSTextManager.writeText("ronda", rondaText.getText());
        }
    }//GEN-LAST:event_writeButtonKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OBSTextManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OBSTextManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OBSTextManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OBSTextManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OBSTextManagerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jugador1Label;
    private javax.swing.JTextField jugador1Text;
    private javax.swing.JLabel jugador2Label;
    private javax.swing.JTextField jugador2Text;
    private javax.swing.JLabel punt1Label;
    private javax.swing.JTextField punt1Text;
    private javax.swing.JLabel punt2Label;
    private javax.swing.JTextField punt2Text;
    private javax.swing.JLabel rondaLabel;
    private javax.swing.JTextField rondaText;
    private javax.swing.JLabel twitter1Label;
    private javax.swing.JTextField twitter1Text;
    private javax.swing.JLabel twitter2Label;
    private javax.swing.JTextField twitter2Text;
    private javax.swing.JButton writeButton;
    // End of variables declaration//GEN-END:variables
}
